In [1]:
print("hello")

hello


In [3]:
import torch

In [4]:
torch.__version__

'2.12.0+cpu'

In [6]:
a =torch.tensor([1,2,3])

In [7]:
a

tensor([1, 2, 3])

In [8]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

Time on CPU: 33.8607 seconds


In [12]:
matrix_cpu1

tensor([[-4.0336e-01, -9.5851e-01, -4.1356e-01,  ...,  1.0194e+00,
          5.6504e-01,  2.3527e-01],
        [-6.5224e-01,  1.0967e-01,  5.2050e-01,  ..., -1.2589e+00,
         -1.6028e+00, -2.0175e-02],
        [-1.3049e-02, -9.7504e-01,  4.4046e-02,  ...,  1.9407e+00,
         -2.2800e-01,  2.0221e+00],
        ...,
        [ 1.4052e+00, -2.9966e-01,  9.3229e-01,  ...,  9.2488e-01,
          1.1590e+00,  1.0088e+00],
        [ 3.8393e-01,  5.1316e-01,  1.5433e+00,  ..., -1.9038e+00,
         -5.6234e-04, -3.3189e-01],
        [-4.8887e-01, -7.8894e-01,  9.6977e-01,  ...,  1.5483e-02,
         -1.5815e-02, -9.1809e-01]])

In [13]:
matrix_cpu2

tensor([[-0.7540, -0.4614,  0.5397,  ...,  0.1864,  1.6507, -0.1205],
        [ 0.2484, -1.0036, -0.1209,  ...,  0.4636, -0.7444,  1.3250],
        [ 0.4454,  0.2079, -0.9399,  ..., -0.3881,  0.7748,  0.1125],
        ...,
        [ 1.4590, -0.5181,  0.7176,  ...,  0.0163, -0.4466,  1.0019],
        [-0.6101, -1.2174,  1.8033,  ...,  0.5397, -1.8336,  0.0605],
        [ 2.2616, -0.0895, -0.6671,  ..., -1.7386, -0.2313,  1.3262]])